### ISSUE TITLE
demo里点击录音没效果

### ISSUE THREAD

**Issue by Liebesgruppe** [bogerchan/Nier-Visualizer#16]
准确的说是在录音情况下，这十种动画效果里，所有包含1，2，3，5，7效果的都不会起作用

**Comment by bogerchan** [comment]
Demo 里的录音情况只返回了 wave 波形数据，没有搞 fft ，有些效果是用 fft 数据接口的，在 Demo 里把 fft 的接口适配下就有数据。:)

**Comment by Liebesgruppe** [comment]
@bogerchan 好的，感谢回复 :)

**Comment by pys200603027** [comment]
你好作者，感想提供这个库，关于录音情况没有动画的问题
```java
//没有效果产生
ColumnarType1Renderer
```
我做了如下修改
`NierVisualizerManager`中

```
fetchWaveData()?.apply {
                        val waveBuffer = mWaveBuffer ?: return@apply
                        if (size != waveBuffer.size) {
                            throw IllegalStateException("NVDataSource must provide correct wave data size as it's getDataLength() says.")
                        }
                        System.arraycopy(this, 0, waveBuffer, 0, size)
                        Log.d("123","updateWaveData")
                        mRenderer.updateWaveData(waveBuffer)
                    }
```

但是获取到的效果似乎是相反的，声音越大，柱状图越低，声音小，柱状图在最大值

请问我该如何处理？

**Comment by pys200603027** [comment]
补充

`ColumnarType1Renderer `类型是 
```override fun getInputDataType() = IRenderer.DataType.WAVE```

按照您上述的“描述Demo 里的录音情况只返回了 wave 波形数据”
`ColumnarType1Renderer`应该是可以做出动画效果的

**Comment by bogerchan** [comment]
> 你好作者，感想提供这个库，关于录音情况没有动画的问题
> 
> ```java
> //没有效果产生
> ColumnarType1Renderer
> ```
> 
> 我做了如下修改
> `NierVisualizerManager`中
> 
> ```
> fetchWaveData()?.apply {
>                         val waveBuffer = mWaveBuffer ?: return@apply
>                         if (size != waveBuffer.size) {
>                             throw IllegalStateException("NVDataSource must provide correct wave data size as it's getDataLength() says.")
>                         }
>                         System.arraycopy(this, 0, waveBuffer, 0, size)
>                         Log.d("123","updateWaveData")
>                         mRenderer.updateWaveData(waveBuffer)
>                     }
> ```
> 但是获取到的效果似乎是相反的，声音越大，柱状图越低，声音小，柱状图在最大值
> 
> 请问我该如何处理？

感谢老铁对该项目的支持，这个问题是个 Bug，我已经在 `v0.1.3` 版本上修复好啦，重新 Pull 下 `master` 分支应该就能看到修复后的代码，如有问题请继续与我联系，:D，具体修复代码：[4d7bded](https://github.com/bogerchan/Nier-Visualizer/commit/4d7bded0e52a833a3359cc1db27456a9af0502df)

**Comment by pys200603027** [comment]
> > 你好作者，感想提供这个库，关于录音情况没有动画的问题
> > ```java
> > //没有效果产生
> > ColumnarType1Renderer
> > ```
> > 
> > 
> > 我做了如下修改
> > `NierVisualizerManager`中
> > ```
> > fetchWaveData()?.apply {
> >                         val waveBuffer = mWaveBuffer ?: return@apply
> >                         if (size != waveBuffer.size) {
> >                             throw IllegalStateException("NVDataSource must provide correct wave data size as it's getDataLength() says.")
> >                         }
> >                         System.arraycopy(this, 0, waveBuffer, 0, size)
> >                         Log.d("123","updateWaveData")
> >                         mRenderer.updateWaveData(waveBuffer)
> >                     }
> > ```
> > 但是获取到的效果似乎是相反的，声音越大，柱状图越低，声音小，柱状图在最大值
> > 请问我该如何处理？
> 
> 感谢老铁对该项目的支持，这个问题是个 Bug，我已经在 `v0.1.3` 版本上修复好啦，重新 Pull 下 `master` 分支应该就能看到修复后的代码，如有问题请继续与我联系，:D，具体修复代码：[4d7bded](https://github.com/bogerchan/Nier-Visualizer/commit/4d7bded0e52a833a3359cc1db27456a9af0502df)

太棒了，亲测有效，感想作者

**Comment by bogerchan** [comment]
客气。:D
