### ISSUE TITLE
能不能做个时域的效果

### ISSUE THREAD

**Issue by zxl777** [bogerchan/Nier-Visualizer#18]
终于找到你了，做得很棒，声音反应也实时够快！比Github上其他Android的库都好，而且还是
kotlin写的，完全满足我的需求，谢谢。

能不能做个时域的效果，就是类似ios中语音备忘录那样的效果。

现在好像都是频域的效果吧？

**Comment by bogerchan** [comment]
我理解的时域是波形数据吧，这两者都有的哈，fft 和 wave 两种类型，你可以看下项目 Demo 哈，如果是语音波形的效果的话，可以自己撸一个，后续有时间我再搞个，感谢老铁支持！ :D
