### ISSUE TITLE
请教 FFT 部分是哪段代码？怎么用一时没看懂

### ISSUE THREAD

**Issue by zxl777** [bogerchan/Nier-Visualizer#19]
RT

**Comment by bogerchan** [comment]
你要自己写可视化效果吗？可以看下 me.bogerchan.niervisualizer.renderer.IRenderer 接口实现，关于字节数组可以参照文档 [文档](https://developer.android.com/reference/android/media/audiofx/Visualizer.html#getFft(byte[]))
