### ISSUE TITLE
有没有办法用Adobe After Effects这样的软件代替画的过程, 然后导入到项目中

### ISSUE THREAD

**Issue by a442509097** [bogerchan/Nier-Visualizer#22]
如上, 如果要画一写复杂的图形(如果早些的那些可视化库), 可否用这些软件代替, 然后用库的方式导入, 目前我知道可用Lottie把 Adobe After Effects制作的动画转换成json导入到项目中, 到好像接口有限, 不能具体控制...

**Comment by bogerchan** [comment]
感谢你的建议，:)， 可视化库是实时渲染的，在移动端实现解析并自动渲染图形，抛开实现的复杂度问题，对性能开销也是比较大的，我计划接下来的几个月对库做个全面性的升级，除了提供更多的可视化效果，也会更关注性能优化以及提升它的易用性和扩展能力，敬请期待。 :D
