### ISSUE TITLE
How to make two animation (two renderers) work with the same visualizerManager?

### ISSUE THREAD

**Issue by jpfsilvaa** [bogerchan/Nier-Visualizer#25]
Hi! This library is awesome. Thank you for that!

I'm working in a project which I need to use a CircleSolidRenderer customized and below that I need to put an ColumnType4Renderer. My problem is that I need both work together, I mean, both shoudl be started by a NierVisualizerManager. I coudn't start them by the same manager and neighter by two separeted managers (using the same media player, only one animation is started)

Could you help me? Is it possible?

**Comment by bogerchan** [comment]
Thank your support, it support that using some renderer together by the same `NierVisualizerManager`, there are some examples in demo module, just like below:
``` 
visualizerManager.start(surfaceView, arrayOf(ColumnarType1Renderer(), AnotherRenderer()...))
```

**Comment by jpfsilvaa** [comment]
Hi!

Yes, I saw an example like this. Bu the both renderers stays centralized and one overlays the other. There's a way of changing the position of these renderers?

**Comment by bogerchan** [comment]
Hi, jpfsilvaa, 
sorry for delay reply, the renderer is calculated by default, I think you can customized it by copy of new one, thanks!
