### ISSUE TITLE
能否支持在没有录音权限时用有录音权限时播放音频生成的数据模拟一样的效果？

### ISSUE THREAD

**Issue by Carlos2927** [bogerchan/Nier-Visualizer#26]
我曾经尝试过，但是不行，只好放弃使用了。主要用作播放语音消息时，这个时候如果弹窗需要获取录音权限会给用户带来误解的。希望作者能够支持一下，谢谢！

**Comment by bogerchan** [comment]
目前还不行，`Visualizer ` 要求有 record 权限，这是 SDK 上写明的了，可以考虑用其他方式播放，只要有波形数据回调就可以直接展示的。
