### ISSUE TITLE
Not sync with Audio

### ISSUE THREAD

**Issue by jmimohsin** [bogerchan/Nier-Visualizer#3]
Animation is still running after audio stop. Animation should stop and play according to Audio stop/play same as I am using Wave visualization project from github.

**Comment by bogerchan** [comment]
Thanks for your advice. I think it's better stop it by your own logic, the visualizer shouldn't care about too much things so that it can be suit for various of scenes.
PS: I plan to upgrade demo project to fix this issue. :D

**Comment by jmimohsin** [comment]
Great! Than it shouldn't require Audio permission :p 

Please check out Wave Visualization and your visualization in app than you will feel that it's necessary.

https://play.google.com/store/apps/details?id=coders.hub.fm.radio

But Thanks for your help and project.

**Comment by bogerchan** [comment]
Thanks for your advice! I have removed it in ver. 0.0.3, and update demo project, it has solved those problems above, please try it. :) 
PS. Your app looks beautiful! :D

**Comment by jmimohsin** [comment]
You didn't updated dependency version?

**Comment by bogerchan** [comment]
The library has been updated to version 0.0.3,
but I forgot update version in doc and will fix it in this weekend. :)

**Comment by jmimohsin** [comment]
Thanks for quick reply, I was updating my app so see this issue again. 

Thanks again... :)

**Comment by bogerchan** [comment]
I have updated some android support libraries version in 0.0.3,  maybe some dependencies are not satisfied,  you can open new issue and post error information if the problem still exist.

**Comment by jmimohsin** [comment]
I have already published app but still animation are not stopping when we are pausing audio same as wave project. :p

I will check other things in my new update. Thanks for your support.
