### ISSUE TITLE
How to use it while Recording Audio?

### ISSUE THREAD

**Issue by shireen028** [bogerchan/Nier-Visualizer#33]
Hi,
The visualisers are working fine with audio files but doesn't seem to work well with recording audio. Like ColumnarType4Renderer(FFT) is not working when recording audio from mic/speaker.

**Comment by chorauoc** [comment]
Hi,

I am also looking for this, any sample code which we can use in java

**Comment by kishorekumarek** [comment]
Hi Any update on this? need sample for recording audio

**Comment by bogerchan** [comment]
Hi, sorry for my late reply, because this renderer only accepts the wave data, so it doesn't display if the input is FFT data, you can use the supported renderers or customize your renderers, I plan to upgrade it to eliminate the difference type data.
