### ISSUE TITLE
java.lang.RuntimeException: Cannot initialize Visualizer engine

### ISSUE THREAD

**Issue by jpjpjp28** [bogerchan/Nier-Visualizer#34]
I am playing a music from a streaming website and run into this error:

`Caused by: java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -3`

Does your library support streaming audio?

**Comment by bogerchan** [comment]
Hi, @jpjpjp28 , thanks for using the library, the error is occurred form [Visualizer](https://developer.android.com/reference/android/media/audiofx/Visualizer), how do you initialize the library?

**Comment by mneckoee** [comment]
@jpjpjp28 
see this:
[Android Visualizer won't pick up audio from Spotify streaming music](https://stackoverflow.com/a/62192082/6133481)
Adding "android.permission.RECORD_AUDIO" to manifest and requesting for runtime permissions fixed the issue
[restart your device if needed](https://stackoverflow.com/a/42704999/6133481)
