### ISSUE TITLE
change visualizer color

### ISSUE THREAD

**Issue by esirahimian** [bogerchan/Nier-Visualizer#38]
Is there a way to change the color visualizer?

**Comment by bogerchan** [comment]
Hi @esirahimian , thanks for using the library!
You can change the colors by your custom renderers, just copy it under the [package](https://github.com/bogerchan/Nier-Visualizer/tree/master/core/src/main/java/me/bogerchan/niervisualizer/renderer).

**Comment by mneckoee** [comment]
for transparent background do this on `SurfaceView`

```
visualizerSurfaceView?.apply {
    // for transparent background
    setBackgroundColor(0)
    setZOrderOnTop(true)
    holder?.setFormat(PixelFormat.TRANSPARENT)
}
```
