### ISSUE TITLE
can it be applied to radio streaming?

### ISSUE THREAD

**Issue by istahilagi** [bogerchan/Nier-Visualizer#42]
can it be applied to radio streaming ?

**Comment by bogerchan** [comment]
Hi, it can, but you need to provide the fft data by yourself.发送自我的盖乐世
-------- 原始信息 --------发件人： istahilagi ***@***.***> 日期: 2022/1/7  19:08  (GMT+08:00) 收件人： bogerchan/Nier-Visualizer ***@***.***> 抄送： Subscribed ***@***.***> 主题： [bogerchan/Nier-Visualizer] can it be applied to radio streaming? (Issue #42) 
can it be applied to radio streaming ?

**Comment by istahilagi** [comment]
I use exo player. can you help, what code should i enter?

**Comment by bogerchan** [comment]
Here is a post to show how to get the audio bytes from ExoPlayer, I think you could try it.
https://medium.com/@subasharyc/easy-visualizer-with-exoplayer-b310e73f677f
